version: "{build}"

os: Visual Studio 2015

platform:
  - Win32
  #- x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

configuration:
  #- Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\LevelSyn

branches:
  only:
    - master

before_build:
  - cd C:\projects\LevelSyn
  - md build
  - cd build
  - git submodule update --init --recursive
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ../

build:
  project: C:\projects\LevelSyn\build\LevelSyn.sln
  parallel: true
  verbosity: normal

after_build:
  - cd C:\projects\LevelSyn\build\src\Release
  - levels.exe ..\..\..\data\planar_graph_fig1.xml ..\..\..\data\building_blocks_fig1.xml ..\..\..\data\config.txt 10
