version: "{build}"

os: Visual Studio 2015

platform:
  - Win32
  #- x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib32-msvc-14.0

configuration:
  #- Debug
  - Release

clone_folder: C:\projects\LevelSyn

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

build_script:
  - cd C:\projects\LevelSyn
  - md build
  - cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ../
  - msbuild %MSBuildOptions% LevelSyn.sln
  - cd ..\bin
  - levels.exe ..\data\planar_graph_fig1.xml ..\data\building_blocks_fig1.xml ..\data\config.txt 10
